### PR TITLE
Adds e2e using crc in Github Actions

### PR DESCRIPTION
**Pull request by PuneetPunamiya**

### CODE REVIEW

**Comment by vdemeester** [comment]
@PuneetPunamiya we need the secret setup right ?

**Comment by PuneetPunamiya** [comment]
> @PuneetPunamiya we need the secret setup right ?

Yes, we will need the secret 👍🏻

**Comment by vdemeester** [comment]
@PuneetPunamiya secret has been added, we can merge whenever you are ok to merge.

**Pull request merged**
